### ISSUE TITLE
Cargo.toml: Consider building docs with all features

### ISSUE THREAD

**Issue by mxinden** [multiformats/rust-multihash#197]
Consider adding the below to your `Cargo.toml` to have all features documented on `docs.rs`:

``` toml
[package.metadata.docs.rs]
all-features = true
```

https://github.com/libp2p/rust-libp2p/blob/6cc3b4ec52c922bfcf562a29b5805c3150e37c75/Cargo.toml#L68-L69

This might be a deliberate choice. Feel free to ignore.
